import Head from "next/head"
import styles from "../styles/Home.module.css"

export default function Home({ posts }) {
  const number = 3
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="title">Home</h1>
      <h2>User List</h2>

      {posts?.map((user) => (
        <div key={user.id}>
          {user.id} - {user.name}
        </div>
      ))}

      <style jsx>
        {`
          .title {
            display: ${number > 2 ? "block" : "none"};
            color: yellow;
          }
        `}
      </style>
    </div>
  )
}

export async function getServerSideProps() {
  const res = await fetch("https://jsonplaceholder.typicode.com/comments")
  const posts = await res.json()

  return {
    props: {
      posts,
    },
  }
}
