import Head from "next/head"
import { useRouter } from "next/router"
import styles from "../styles/Home.module.css"

export default function Home({ users }) {
  const router = useRouter()
  const number = 3
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="title">Home</h1>
      <h2>User List</h2>

      {!!users &&
        users.map((user) => (
          <h4 key={user.id} onClick={() => router.push(`user/${user.id}`)}>
            {user.id} - {user.name}
          </h4>
        ))}

      <style jsx>
        {`
          .title {
            display: ${number > 2 ? "block" : "none"};
            color: yellow;
          }
          h4 {
            cursor: pointer;
          }
          h4:hover {
            color: red;
          }
        `}
      </style>
    </div>
  )
}

export async function getStaticProps() {
  const res = await fetch("https://jsonplaceholder.typicode.com/users")
  const users = await res.json()

  return {
    props: {
      users,
    },
  }
}
